#!/bin/sh

# Author:     Héctor Molinero Fernández <hector@molinero.dev>
# Repository: https://github.com/hectorm/music-dl
# License:    MIT, https://opensource.org/licenses/MIT

set -eu

printAction() {
	printf -- '\033[1;33m + \033[1;32m%s \033[0m\n' "$@"
}

OUT_DIR="${HOME}/Downloads/music-dl"
mkdir -p "${OUT_DIR}"

TMP_DIR=$(mktemp -dt music-dl.XXXXXXXX)
trap 'rm -rf ${TMP_DIR:?}' EXIT

printAction 'Downloading files...'
youtube-dl \
	--no-continue \
	--format 'bestaudio' \
	--output "${TMP_DIR}/%(title)s.%(ext)s" \
	--default-search 'ytsearch' \
	-- "$@"

printAction 'Encoding files to VBR MP3 and trimming silence...'
for file in "${TMP_DIR}"/*; do
	outFile=${file%.*}.mp3
	tmpFile=$(mktemp -ut .XXXXXXXX.mp3 -p "${TMP_DIR}")
	silenceremove='start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak'
	filters="silenceremove=${silenceremove},aformat=dblp,areverse,silenceremove=${silenceremove},aformat=dblp,areverse"
	ffmpeg -hide_banner -i "${file}" -codec:a libmp3lame -qscale:a 2 -af "${filters}" "${tmpFile}"
	rm -f "${file}"; mv -f "${tmpFile}" "${outFile}"
done

if command -v eyeD3 >/dev/null; then
	printAction 'Cleaning metadata using eyeD3...'
	find "${TMP_DIR}" -type f -name '*.mp3' -exec eyeD3 --remove-all '{}' ';'
elif command -v id3convert >/dev/null; then
	printAction 'Cleaning metadata using id3lib...'
	find "${TMP_DIR}" -type f -name '*.mp3' -exec id3convert --strip '{}' ';'
elif command -v mat >/dev/null; then
	printAction 'Cleaning metadata using MAT...'
	find "${TMP_DIR}" -type f -name '*.mp3' -exec mat '{}' ';'
fi

printAction 'Moving files to output directory...'
find "${TMP_DIR}" -type f -name '*.mp3' -exec mv -f '{}' "${OUT_DIR}"/ ';'
