#!/bin/sh

# Author:     Héctor Molinero Fernández <hector@molinero.dev>
# Repository: https://github.com/hectorm/music-dl
# License:    MIT, https://opensource.org/licenses/MIT

set -eu
export LC_ALL='C'

printInfo() { [ -t 1 ] && printf '\033[0m[\033[1;32mINFO\033[0m] %s\n' "${@}" || printf '[INFO] %s\n' "${@}"; }
printWarn() { [ -t 1 ] && printf '\033[0m[\033[1;33mWARN\033[0m] %s\n' "${@}" >&2 || printf '[WARN] %s\n' "${@}" >&2; }
printError() { [ -t 1 ] && printf '\033[0m[\033[1;31mERROR\033[0m] %s\n' "${@}" >&2 || printf '[ERROR] %s\n' "${@}" >&2; }

main() {
	outDir="${DESTDIR:-${HOME:?}/Downloads/}"
	[ -e "${outDir:?}" ] || mkdir -p "${outDir:?}"

	tmpDir="$(mktemp -dt music-dl.XXXXXXXX)"
	# shellcheck disable=SC2154
	trap 'ret="$?"; rm -rf -- "${tmpDir:?}"; trap - EXIT; exit "${ret:?}"' EXIT TERM INT HUP

	ffmpegCmd=''
	if command -v ffmpeg >/dev/null; then ffmpegCmd='ffmpeg'
	else
		printError 'ffmpeg is required for this script'
		exit 1
	fi

	ytDlpCmd=''
	if command -v yt-dlp >/dev/null; then ytDlpCmd='yt-dlp'
	elif command -v youtube-dl >/dev/null; then ytDlpCmd='youtube-dl'
	else
		printError 'yt-dlp or youtube-dl are required for this script'
		exit 1
	fi

	printInfo 'Downloading files...'
	"${ytDlpCmd:?}" \
		--no-continue \
		--format 'bestaudio' \
		--output "${tmpDir:?}/%(title)s.%(ext)s" \
		--default-search 'ytsearch' \
		-- "$@"

	printInfo 'Encoding files to VBR MP3 and trimming silence...'
	for inFile in "${tmpDir:?}"/*; do
		outFile="${outDir:?}/${inFile##*/}"; outFile="${outFile%.*}.mp3"
		silenceremove='start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak'
		filters="silenceremove=${silenceremove:?},aformat=dblp,areverse,silenceremove=${silenceremove:?},aformat=dblp,areverse"
		"${ffmpegCmd:?}" -hide_banner -i "${inFile:?}" -codec:a libmp3lame -qscale:a 2 -af "${filters:?}" -map_metadata -1 -fflags +bitexact -y "${outFile:?}"
	done
}

main "${@-}"
